export const HOLDING_FORM = 'HOLDING_FORM'
export const GET_HOLDINGS = 'GET_HOLDINGS'
export const ADD_HOLDING = 'ADD_HOLDING'
export const VALIDATE_FORM = 'VALIDATE_FORM'
export const CURRENT_HOLDING = 'CURRENT_HOLDING'
export const SELL_HOLDING = 'SELL_HOLDING'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
