version: '3.8'
services:
  node:
    container_name: api
    restart: always
    build: .
    ports: 
      - "3030:3030"
    volumes:
      - ./:/code
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:

  